apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-two
  labels:
    app: nginx-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-two
  template:
    metadata:
      labels:
        app: nginx-two
    spec:
      containers:
        - name: nginx-two
          image: nginx:1.14.2
          ports:
            - containerPort: 80
