---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: one
  namespace: default
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: one
    repoURL: https://github.com/1aziz/argocd-pg/
    targetRevision: HEAD
