---
apiVersion: v2
name: argocd
description: Install Argo CD

type: application

version: 0.1.0

dependencies:
  - name: argo-cd
    version: 5.5.19
    repository: https://argoproj.github.io/argo-helm
